In [ ]:
#import libraries
import numpy as np
import pandas as pd

In [ ]:
#importing data 
data = pd.read_csv("data_samples.csv")


In [ ]:
print(data)

        -81527.8125  -17151.26171875  ...  -74632.5078125   left
0     -81529.773438    -17151.833984  ...   -74641.140625   left
1     -81535.679688    -17153.121094  ...   -74653.492188   left
2     -81536.968750    -17152.597656  ...   -74658.023438   left
3     -81532.250000    -17148.257812  ...   -74656.546875   left
4     -81537.593750    -17152.882812  ...   -74661.117188   left
...             ...              ...  ...             ...    ...
49994 -77034.812500    -15287.067383  ...   -73124.132812  right
49995 -77029.476562    -15283.346680  ...   -73115.687500  right
49996 -77017.984375    -15273.094727  ...   -73096.093750  right
49997 -77017.507812    -15277.578125  ...   -73090.132812  right
49998 -77012.593750    -15275.527344  ...   -73086.890625  right

[49999 rows x 20 columns]


In [ ]:
#shuffling the data as 2differnt files for 2 different classes has been concatenated
from sklearn.utils import shuffle

dataset = shuffle(data)

In [ ]:
print(dataset)

        -81527.8125  -17151.26171875  ...  -74632.5078125   left
34194 -89803.320312    -19152.738281  ...   -79717.070312  right
10116 -75418.007812    -14471.054688  ...   -72196.304688   left
17180 -73859.507812    -13276.291992  ...   -71074.109375   left
12979 -74665.460938    -13840.867188  ...   -71629.148438   left
3449  -79612.453125    -16278.553711  ...   -74149.382812   left
...             ...              ...  ...             ...    ...
2311  -80222.234375    -16671.992188  ...   -74421.460938   left
22853 -73101.484375    -12758.017578  ...   -70681.437500   left
38791 -85697.664062    -18184.806641  ...   -76868.593750  right
33647 -90376.671875    -19254.304688  ...   -80139.835938  right
37622 -86649.140625    -18419.839844  ...   -77592.765625  right

[49999 rows x 20 columns]


In [ ]:
#Splitting the data into X and y
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[-89803.3203125  -19152.73828125  22611.23828125 ... -27659.75390625
  -93935.0234375  -79717.0703125 ]
 [-75418.0078125  -14471.0546875   26796.48632812 ... -24497.22460938
  -70342.59375    -72196.3046875 ]
 [-73859.5078125  -13276.29199219  27694.51367188 ... -23838.47460938
  -67703.203125   -71074.109375  ]
 ...
 [-85697.6640625  -18184.80664062  23335.84179688 ... -26940.0625
  -86723.90625    -76868.59375   ]
 [-90376.671875   -19254.3046875   22531.94140625 ... -27698.61523438
  -94971.1875     -80139.8359375 ]
 [-86649.140625   -18419.83984375  23070.48046875 ... -27356.19726562
  -88378.6328125  -77592.765625  ]]


In [ ]:
print(y)

['right' 'left' 'left' ... 'right' 'right' 'right']


In [ ]:
# encoding the dependent variable because they are in strings
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 0 0 ... 1 1 1]


In [ ]:
#splitting the dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
# standardizing the X_train and X_test
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# applying logestic regression
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(max_iter=10000, solver = 'lbfgs')
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# applying kernel SVM
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
# applying Random Forest
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
#predicting using Random Forest gave the highest accuracy 
y_pred = classifier.predict(X_test)

print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [1 1]
 [0 0]
 [0 0]]


In [ ]:
# printing the confusion matrix and accuracy
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[6279    3]
 [   4 6214]]


0.99944